chore(gha): Fix release workflow for component construction (#3359)
<!-- markdownlint-disable MD041 -->
#### What this PR does / why we need it

The release workflow for constructing the component version for
`0.14.0-rc.1`
[failed](https://github.com/open-component-model/open-component-model/actions/runs/31510360804/job/93846975917):

```
Error: failed to render components recursively: 
constructing component versions failed: f
ailed to constructComponent components from graph:
failed to process component constructor graph: 
failed to process value for node name=ocm.software/cli,version=0.14.0-rc.1 in graph: 
failed processing constructor component: 
error constructing component "name=ocm.software/cli,version=0.14.0-rc.1": 
error constructing component: 
error processing resource "architecture=amd64,name=cli,os=darwin,version=0.14.0-rc.1" at index 2: 
error processing resource "architecture=amd64,name=cli,os=darwin,version=0.14.0-rc.1" with digest processor: 
error downloading resource for digest processing: 
error creating temporary file for https://github.com/open-component-model/open-component-model/releases/download/v0.14.0-rc.1/ocm-darwin-amd64: open /tmp/ocm-wget-download-1588852822: 
no such file or directory
```

The cause for this is the digest processing for `wget`. This requires a
`tmp` directory that is not present in the container. This PR adds a
temporary directory to the container. (I think we could've adjusted this
with the filesystem config as well but mounting `tmp` is more
error-prone). I tested this locally and it worked.

Unfortunately, this fix needs to be backported to the branch
`releases/0.14` as the release workflow calls the component construction
workflow from that release branch:

```
Uses: open-component-model/open-component-model/.github/workflows/publish-components.yml@refs/heads/releases/v0.14 (6c4a31a07e2053978f68cb5bf6ea82957183f8bd)
```

Additionally, I cleaned up another component construction workflow that
is unused

---------

Signed-off-by: Frederic Wilhelm <frederic.wilhelm@sap.com>