chore(GHA): remove branch-suffix input (#2920)
<!-- markdownlint-disable MD041 -->
#### What this PR does / why we need it

The release for `0.9.0`
[failed](https://github.com/open-component-model/open-component-model/actions/runs/26824468590/job/82945728315)
because the `branch-suffix` contains an invalid value:

> Error: Branch suffix '0.9.0' is not a valid value. Unable to continue.

According to the
[docs](https://github.com/peter-evans/create-pull-request#alternative-strategy---always-create-a-new-pull-request-branch)
the value needs to be `random`, `timestamp`, or `short-commit-hash`.
Based on the previous implementation, I removed the `branch-suffix` and
appended the version to the branch name directly.

Signed-off-by: Frederic Wilhelm <frederic.wilhelm@sap.com>